### ISSUE TITLE
Not using the free lookup API.

### ISSUE THREAD

**Issue by ellisio** [stuyam/laravel-phone-validator#1]
Currently your validator claims to be using the free lookup API. However, digging into the validator you are trying to [call the `->carrier` attribute on the response](https://github.com/stuyam/laravel-phone-validator/blob/master/src/PhoneValidatorServiceProvider.php#L33). That is a paid resource on the LookUp API:

![image](https://cloud.githubusercontent.com/assets/127468/21817374/bb847d7e-d731-11e6-947a-c3bcf691536b.png)

It also should be noted you are using the old `4.x` SDK; Twilio now recommends using the `5.x` SDK.

Cheers

**Comment by stuyam** [comment]
Have you tried this? I know it appears that way, but the way I am requesting it it actually still uses the free service. I have hundreds of requests on my Twilio accounts and they are all free. Originally I was getting a value off the carrier itself which cost $0.005 per request, but I changed it to the way that it is now because they way that it is now it free.

Have you tested it? All of the requests on http://validators.stuyam.com/ are free on my Twilio account. I don't have a good answer to why this is the case but I think it only costs more when you pull from the carrier but the carrier is meant to be used as a test for the numbers validity.

<img width="1170" alt="screenshot 2017-01-10 13 32 23" src="https://cloud.githubusercontent.com/assets/1553779/21819351/5a9b7c08-d739-11e6-8297-20aea2571b5d.png">

You can see from the screenshot (Account details from June) that originally I was testing by pulling a value off the carrier and it was costing me but when I switched to how I am using it now it is free. As you can see from the free requests in the second row of the screenshots.

**Comment by ellisio** [comment]
Calling this code through artisan tinker:

```
$client->lookups
    ->phoneNumbers($number)
    ->fetch(['type' => 'carrier']);
```

Triggers a carrier lookup that costs us $0.005. That returns a JSON result of:

```
{
  "caller_name": null,
  "country_code": "US",
  "phone_number": "<redacted>",
  "national_format": "<redacted>",
  "carrier": {
    "mobile_country_code": "310",
    "mobile_network_code": "150",
    "name": "AT&T Wireless",
    "type": "mobile",
    "error_code": null
  },
  "add_ons": null,
  "url": "https://lookups.twilio.com/v1/PhoneNumbers/<redacted>?Type=carrier"
}
```

Calling this code in tinker:

```
$client->lookups
    ->phoneNumbers($number)
    ->fetch();
```

Results in the following JSON with a cost of $0.00:

```
{
  "caller_name": null,
  "country_code": "US",
  "phone_number": "<redacted>",
  "national_format": "<redacted>",
  "carrier": null,
  "add_ons": null,
  "url": "https://lookups.twilio.com/v1/PhoneNumbers/<redacted>"
}
```

**Comment by ellisio** [comment]
![image](https://cloud.githubusercontent.com/assets/127468/21819684/bc54bd78-d73a-11e6-8488-27e0c23939a4.png)

Those 4 Carrier lookups were me testing in Tinker with the carrier lookup code. The 300 and some odd others are with me removing that carrier lookup and just using the `RestException` catch statement as the flag for invalid numbers.

**Comment by stuyam** [comment]
Awesome @ellisio thanks for the research! Can you run another test for me? Just for testing purposes with the same setup, does running what I have in my code `$client->phone_numbers->get($number)->carrier;` on 4.x Twilio SDK also charge you for phone lookups?

Thanks for the investigative work!
